# The URL the site will be built for
base_url = "https://josephcatrambone.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme Config
theme = "apollo"
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
comment = false
mathjax = true
mathjax_dollar_inline_enable = true
repo_view = true
repo_url = "https://github.com/JosephCatrambone/blog/tree/main/content/"

socials = [
  { name = "github", url = "https://github.com/JosephCatrambone/", icon = "github" },
]
menu = [
  { name = "Projects", url = "/projects", weight = 1 },
  { name = "Stories", url = "/stories", weight = 2 },
  { name = "Tag Search", url = "/tags", weight = 3 },
  { name = "Archived Posts", url = "/blog_arvhice", weight = 4 },
]

