# The URL the site will be built for
base_url = "https://www.josephcatrambone.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
theme = "radion"

[extra]
# Put all your custom variables here
paginate_by = 5
github = "https://github.com/JosephCatrambone"
