---
title: 'Little Awful Jam 2018: Conclusions and Post-Mortem'
description: ""
published: 2018-01-22
redirect_from: 
            - https://www.josephcatrambone.com/?p=1080
categories: "Game, Programming, Rant"
hero: ./img/wp-content-uploads-debatesim.png
---
It's done enough!![](./img/wp-content-uploads-debatesim.png)tl;dr: [Download a Runnable Jar Here](https://www.josephcatrambone.com/games/debatesimulator/debatesimulator.jar)Standalone PC/OSX builds are pending.Kudos to [Peter Queckenstedt (@scutanddestroy)](https://twitter.com/scutanddestroy?s=09) for doing an amazing job on the Proctor, Hillary, and Trump.

### Post-Mortem:

​This has been a positive experience. I love games that actually have nontrivial interactions in them and completely open-ended text inputs. I'm a fan of interactive fiction, but hate that feeling when you're digging around and grasping for action words like some sort of textual pixel-hunt.The language processing systems in DS2016 aren't particularly complicated, but they're more simple than I'd like. In the first week of the jam I started writing a recurrent neural network to parse and analyze the sentiment of the player's comments. I realized, perhaps too late, that there wasn't enough clean data for me to use to accurately gauge the sentiment and map it to social groups. Instead, I wrote a basic multinomial naive bayes classifier that takes a sentence, tokenizes it, and maps it to 'like' or 'dislike'. Each group has its own classifier and tokenizer, so I could program demographics with a base voting likelihood and give each of them a few sentences on the "agrees with" and "disagrees with" sides, then have them automatically parse and change their feelings towards the player.A usability change that came in later than one would guess was as follows: I had originally grabbed the demographic with the largest emotional response to a comment and displayed them with the sentiment change. Unfortunately, this turned out to over-exaggerate one particularly noisy group. Another change, shortly thereafter, was masking the exact amount of the change. Instead of saying +1.05% opinion, it simply became "+Conservatives" or "-Hipsters". This was visually far easier to parse and I think helped the overall readability of the game.There is still a call to add some more direct public opinion tracking in the game, letting players know in closer to real time how they're doing among the demographics. I may find it in myself to introduce that.The last interesting aspect that I noticed during playtesting: I had slightly over-tuned the language models to my style of writing. Instead of opining on matters at any length, people were making enormous run-on sentences which appealed to every demographic at the same time. These statements, often self-contradictory, were not something I expected or handled well. I found the game to be rather difficult, but it looks like playtesters had a dandy time making the states go all blue.
